-- Target Modeling Workspace V2: additive P0 contracts and security foundation.
-- Apply only after the 20260911 Target Intelligence and 20260912 Target
-- Modeling migrations. This migration does not enable the V2 UI.
-- Rollback/disable procedure: 20260913_target_modeling_workspace_v2_foundation.rollback.sql

BEGIN;

ALTER TABLE public.ti_admin_settings
  ADD COLUMN IF NOT EXISTS target_modeling_workspace_v2 BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.ti_workspaces
  ADD COLUMN IF NOT EXISTS previous_status TEXT,
  ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS archive_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_step TEXT NOT NULL DEFAULT 'overview',
  ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS original_question TEXT,
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE public.ti_workspaces DROP CONSTRAINT IF EXISTS ti_workspaces_status_check;
ALTER TABLE public.ti_workspaces ADD CONSTRAINT ti_workspaces_status_check CHECK (status IN (
  'draft', 'planning', 'ready_for_collection', 'collecting', 'data_review',
  'ready_for_training', 'training', 'candidate_review', 'ready_for_deployment',
  'deploying', 'ready', 'archived', 'deleting', 'deleted', 'failed',
  'cancelling', 'cancelled', 'planned', 'awaiting_confirmation', 'curating',
  'evaluating', 'awaiting_deployment_confirmation', 'expired', 'rejected',
  'not_ready'
));

ALTER TABLE public.ti_workspaces DROP CONSTRAINT IF EXISTS ti_workspaces_last_step_check;
ALTER TABLE public.ti_workspaces ADD CONSTRAINT ti_workspaces_last_step_check CHECK (last_step IN (
  'overview', 'plan', 'data', 'datasets', 'training', 'review', 'deploy', 'playground'
));

ALTER TABLE public.ti_workspaces DROP CONSTRAINT IF EXISTS ti_workspaces_version_check;
ALTER TABLE public.ti_workspaces ADD CONSTRAINT ti_workspaces_version_check CHECK (version >= 1);

CREATE TABLE IF NOT EXISTS public.ti_workspace_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.ti_workspaces(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'reviewer', 'viewer', 'admin')),
  invited_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  accepted_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.ti_workspace_target_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_target_id UUID NOT NULL REFERENCES public.ti_workspace_targets(id) ON DELETE CASCADE,
  workspace_id UUID NOT NULL REFERENCES public.ti_workspaces(id) ON DELETE CASCADE,
  run_id UUID NOT NULL REFERENCES public.ti_runs(id) ON DELETE RESTRICT,
  report_id UUID NOT NULL REFERENCES public.ti_reports(id) ON DELETE RESTRICT,
  source_snapshot_hash TEXT NOT NULL CHECK (source_snapshot_hash ~ '^[0-9a-f]{64}$'),
  added_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  decision TEXT NOT NULL CHECK (decision IN ('same_run', 'add_to_current', 'create_new')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_target_id, run_id, report_id)
);

CREATE TABLE IF NOT EXISTS public.ti_job_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES public.ti_workspaces(id) ON DELETE CASCADE,
  actor_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  job_id UUID,
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
  entity_type TEXT NOT NULL CHECK (entity_type IN (
    'study', 'collection_job', 'dataset', 'training_run', 'model_artifact', 'deployment'
  )),
  event_type TEXT NOT NULL CHECK (char_length(event_type) BETWEEN 1 AND 100),
  status TEXT CHECK (status IS NULL OR char_length(status) BETWEEN 1 AND 80),
  progress_percent INTEGER CHECK (progress_percent IS NULL OR progress_percent BETWEEN 0 AND 100),
  safe_message TEXT CHECK (safe_message IS NULL OR char_length(safe_message) <= 500),
  public_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (workspace_id, sequence)
);

CREATE INDEX IF NOT EXISTS idx_ti_workspace_members_user
  ON public.ti_workspace_members(user_id, workspace_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_ti_workspace_target_sources_workspace
  ON public.ti_workspace_target_sources(workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ti_job_events_workspace_sequence
  ON public.ti_job_events(workspace_id, sequence DESC);
CREATE INDEX IF NOT EXISTS idx_ti_job_events_job
  ON public.ti_job_events(job_id, sequence DESC) WHERE job_id IS NOT NULL;

DROP TRIGGER IF EXISTS ti_workspace_members_updated_at ON public.ti_workspace_members;
CREATE TRIGGER ti_workspace_members_updated_at
  BEFORE UPDATE ON public.ti_workspace_members
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

ALTER TABLE public.ti_workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ti_workspace_target_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ti_job_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.can_access_ti_workspace(
  p_workspace_id UUID,
  p_roles TEXT[] DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT
    EXISTS (
      SELECT 1 FROM public.ti_workspaces AS workspace
      WHERE workspace.id = p_workspace_id
        AND workspace.user_id = (SELECT auth.uid())
        AND workspace.deleted_at IS NULL
    )
    OR COALESCE(public.is_admin(), FALSE)
    OR EXISTS (
      SELECT 1 FROM public.ti_workspace_members AS member
      WHERE member.workspace_id = p_workspace_id
        AND member.user_id = (SELECT auth.uid())
        AND member.accepted_at IS NOT NULL
        AND member.revoked_at IS NULL
        AND (p_roles IS NULL OR member.role = ANY (p_roles))
    );
$$;

REVOKE ALL ON FUNCTION public.can_access_ti_workspace(UUID, TEXT[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.can_access_ti_workspace(UUID, TEXT[]) TO authenticated;

INSERT INTO public.ti_workspace_members (workspace_id, user_id, role, invited_by, accepted_at)
SELECT workspace.id, workspace.user_id, 'owner', workspace.user_id, workspace.created_at
FROM public.ti_workspaces AS workspace
ON CONFLICT (workspace_id, user_id) DO NOTHING;

CREATE OR REPLACE FUNCTION public.create_ti_workspace_owner_membership()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.ti_workspace_members (
    workspace_id, user_id, role, invited_by, accepted_at
  ) VALUES (
    NEW.id, NEW.user_id, 'owner', NEW.user_id, NOW()
  )
  ON CONFLICT (workspace_id, user_id) DO UPDATE
    SET role = 'owner', accepted_at = COALESCE(public.ti_workspace_members.accepted_at, EXCLUDED.accepted_at), revoked_at = NULL;
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.create_ti_workspace_owner_membership() FROM PUBLIC;
DROP TRIGGER IF EXISTS ti_workspaces_create_owner_membership ON public.ti_workspaces;
CREATE TRIGGER ti_workspaces_create_owner_membership
  AFTER INSERT ON public.ti_workspaces
  FOR EACH ROW EXECUTE FUNCTION public.create_ti_workspace_owner_membership();

DROP POLICY IF EXISTS "TI members read accessible memberships" ON public.ti_workspace_members;
CREATE POLICY "TI members read accessible memberships"
  ON public.ti_workspace_members FOR SELECT TO authenticated
  USING (public.can_access_ti_workspace(workspace_id, NULL));

DROP POLICY IF EXISTS "TI owners and admins manage memberships" ON public.ti_workspace_members;
CREATE POLICY "TI owners and admins manage memberships"
  ON public.ti_workspace_members FOR ALL TO authenticated
  USING (public.can_access_ti_workspace(workspace_id, ARRAY['owner', 'admin']))
  WITH CHECK (public.can_access_ti_workspace(workspace_id, ARRAY['owner', 'admin']));

DROP POLICY IF EXISTS "TI members read target provenance" ON public.ti_workspace_target_sources;
CREATE POLICY "TI members read target provenance"
  ON public.ti_workspace_target_sources FOR SELECT TO authenticated
  USING (public.can_access_ti_workspace(workspace_id, NULL));

DROP POLICY IF EXISTS "TI editors add target provenance" ON public.ti_workspace_target_sources;
CREATE POLICY "TI editors add target provenance"
  ON public.ti_workspace_target_sources FOR INSERT TO authenticated
  WITH CHECK (
    added_by = (SELECT auth.uid())
    AND public.can_access_ti_workspace(workspace_id, ARRAY['owner', 'admin', 'editor'])
  );

DROP POLICY IF EXISTS "TI members read safe job events" ON public.ti_job_events;
CREATE POLICY "TI members read safe job events"
  ON public.ti_job_events FOR SELECT TO authenticated
  USING (public.can_access_ti_workspace(workspace_id, NULL));

REVOKE ALL ON public.ti_workspace_members FROM anon;
REVOKE ALL ON public.ti_workspace_target_sources FROM anon;
REVOKE ALL ON public.ti_job_events FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ti_workspace_members TO authenticated;
GRANT SELECT, INSERT ON public.ti_workspace_target_sources TO authenticated;
GRANT SELECT ON public.ti_job_events TO authenticated;

-- Supabase Realtime Postgres Changes provides the Study WebSocket transport.
-- Event volume is bounded and ti_job_events RLS protects each subscriber.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (
       SELECT 1 FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime'
         AND schemaname = 'public'
         AND tablename = 'ti_job_events'
     ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.ti_job_events';
  END IF;
END;
$$;

DROP FUNCTION IF EXISTS public.get_ti_capabilities();
CREATE OR REPLACE FUNCTION public.get_ti_capabilities()
RETURNS TABLE (
  enabled BOOLEAN,
  access_mode TEXT,
  chat_layout TEXT,
  target_modeling_workspace_v2 BOOLEAN,
  public_daily_analyses INTEGER,
  authenticated_daily_analyses INTEGER,
  max_uploads_per_analysis INTEGER,
  max_upload_bytes BIGINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT settings.enabled, settings.access_mode, settings.chat_layout,
    settings.target_modeling_workspace_v2, settings.public_daily_analyses,
    settings.authenticated_daily_analyses, settings.max_uploads_per_analysis,
    settings.max_upload_bytes
  FROM public.ti_admin_settings AS settings
  WHERE settings.setting_key = 'global'
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.get_ti_capabilities() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_ti_capabilities() TO anon, authenticated;

COMMENT ON COLUMN public.ti_admin_settings.target_modeling_workspace_v2 IS
  'Disabled-by-default rollout gate for the production Study Workspace.';
COMMENT ON TABLE public.ti_workspace_members IS
  'Accepted Study membership and role assignments.';
COMMENT ON TABLE public.ti_workspace_target_sources IS
  'Immutable target selection provenance and explicit cross-run Study decision.';
COMMENT ON TABLE public.ti_job_events IS
  'Bounded user-safe job events for Supabase Realtime and polling replay.';

COMMIT;
